### ISSUE TITLE
Error: java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#20]
Came across this error. Can you take a look at it and try to solve it?
```
[13:35:22] [Server thread/INFO]: Player123 issued server command: /trade PlayerA
[13:35:29] [Server thread/INFO]: PlayerABC issued server command: /trade Player123
[13:35:41] [Server thread/INFO]: StaffplayerA1 issued server command: /tradeplus spectate PlayerABC Player123
[13:35:54] [Server thread/WARN]: [TradePlus] Task #1495848 for TradePlus v2.55 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181]
	at com.trophonix.tradeplus.trade.Trade.lambda$checkAcceptance$20(Trade.java:454) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-342]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-342]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-342]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-342]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-342]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-342]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

Paper version git-Paper-342 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Tradeplus 2.55-1.13

**Comment by Trophonix** [comment]
Looking into it now.

**Comment by Trophonix** [comment]
Fixed in https://github.com/Trophonix/TradePlus/commit/65fd8f4f1ce9f6bead01f371551393575d0a1235

Will be live in the next update coming shortly.
