### ISSUE TITLE
Experience progress must be between 0.0 and 1.0 (NaN)

### ISSUE THREAD

**Issue by TakoidGit** [Trophonix/TradePlus#42]
```
[22:23:52 WARN]: [TradePlus] Task #3605865 for TradePlus v3.54 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.14.3.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.setExp(CraftPlayer.java:1118) ~[patched_1.14.3.jar:git-Paper-117]
        at com.trophonix.tradeplus.util.Experience.changeExp(Experience.java:72) ~[?:?]
        at com.trophonix.tradeplus.extras.ExperienceExtra.onTradeEnd(ExperienceExtra.java:28) ~[?:?]
        at com.trophonix.tradeplus.trade.Trade.lambda$checkAcceptance$19(Trade.java:584) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-117]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-117]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-117]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-117]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

This error occurred when two players were trading exp in the End world. The exp was not received by the other player in the trade.

**Comment by Trophonix** [comment]
I switched to new xp code that seems to be working consistently
