### ISSUE TITLE
TradePlus not working after updating to 1.16.5

### ISSUE THREAD

**Issue by MilesBHuff** [Trophonix/TradePlus#81]
I paid for the plugin, and am running TradePlus v3.81.0.  It does not work on my 1.16.5 Paper server.  Players run `/trade`, and no trade window appears.  Worse:  players become frozen in-place, unable to move until they relog.
```
[22:20:55] [Server thread/INFO]: Swenthorian issued server command: /trade ZerkBagu
[22:20:55] [Server thread/INFO]: ZerkBagu issued server command: /trade Swenthorian
[22:20:55] [Server thread/ERROR]: [global] TaskChain Exception on com.trophonix.tradeplus.trade.Trade$$Lambda$7093/0x00000008021c78b8: Index 0 out of bounds for length 0
[22:20:55] [Server thread/ERROR]: [global] Current Action Index was: 2
[22:20:55] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[22:20:55] [Server thread/WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[22:20:55] [Server thread/WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[22:20:55] [Server thread/WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[22:20:55] [Server thread/WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[22:20:55] [Server thread/WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[22:20:55] [Server thread/WARN]:        at com.trophonix.tradeplus.trade.Trade.updateExtras(Trade.java:645)
[22:20:55] [Server thread/WARN]:        at com.trophonix.tradeplus.trade.Trade.lambda$new$3(Trade.java:144)
[22:20:55] [Server thread/WARN]:        at com.trophonix.tradeplus.shaded.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[22:20:55] [Server thread/WARN]:        at com.trophonix.tradeplus.shaded.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[22:20:55] [Server thread/WARN]:        at com.trophonix.tradeplus.shaded.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[22:20:55] [Server thread/WARN]:        at com.trophonix.tradeplus.shaded.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1194)
[22:20:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[22:20:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[22:20:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427)
[22:20:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[22:20:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
[22:20:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[22:20:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:20:55] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
The issue also occurred in version 3.79.2, which is the latest version available on GitHub;   but players weren't frozen in-place.

**Comment by MilesBHuff** [comment]
Hey, I literally just paid $7.50 for this plugin.  A reply would be nice.

**Comment by Trophonix** [comment]
I will do some testing with latest releases of 1.16 and fix the issue soon.
Sorry for the inconvenience.

**Comment by MilesBHuff** [comment]
Thank you!  Worth noting:  I'm on Java 16.  I have a suspicion that that is why;  but I'm unable to downgrade because some plugins require it now.

**Comment by MilesBHuff** [comment]
Just updated to the latest version on the Spigot website.  Plugin is still broken in exactly the same way.  I paid you $7.50 to fix this almost half a year ago.  What is going on, lol.  Players are upset and there's nothing I can do.
