### ISSUE TITLE
latest version doesn't support 1.12.2....

### ISSUE THREAD

**Issue by SladeHazard** [Trophonix/TradePlus#97]
[14:27:28 ERROR]: Could not pass event InventoryClickEvent to TradePlus v3.84
java.lang.NoSuchMethodError: org.bukkit.Material.isAir()Z
        at com.trophonix.tradeplus.trade.Trade.onClick(Trade.java:287) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1459.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(:70) ~[server.jar:git-Paper-2116373]
        at co.aikar.timings.TimedEventExecutor.execute(:78) ~[server.jar:git-Paper-2116373]
        at org.bukkit.plugin.RegisteredListener.callEvent(:62) ~[server.jar:git-Paper-2116373]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:513) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(:2014) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(:23) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(:10) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(:14) ~[server.jar:git-Paper-2116373]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_333]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_333]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(:46) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(:854) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(:431) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[server.jar:git-Paper-2116373]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]
        
        when clicking on confirm

**Comment by Trophonix** [comment]
Thank you, I will fix this shortly!
